version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
    - 'postgres_data:/var/lib/postgresql/data'
    environment:
    - POSTGRES_DB=db_tictactoe
    - POSTGRES_USER=user_postgres
    - POSTGRES_PASSWORD=pass_postgres
    ports:
    - '5432:5432'
  web:
    build: ./django
    command: bash -c "python manage.py migrate && gunicorn restbase.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    expose:
      - 8000
    restart: always
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - 80:80
    restart: always
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
