# Generated by Django 4.2.2 on 2023-08-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from tictactoe_app.models import Match
from users_app.models import User


def load_initial(apps, schema_editor):
    u1 = User.objects.get(id=1)
    u2 = User.objects.get(id=2) 
    m = Match(player1=u1,player2=u2, finish=True, turn=9, winner=u1, row0column0=u1, row0column1=u2, row0column2=u2, row1column0 = u2, row1column1 = u1, row1column2 = u1, row2column1 = u2, row2column2 = u1)
    m.save()

def unload_initial(apps, schema_editor):
    User.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False)),
                ('turn', models.IntegerField(default=1)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player2', to=settings.AUTH_USER_MODEL)),
                ('row0column0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row0column0', to=settings.AUTH_USER_MODEL)),
                ('row0column1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row0column1', to=settings.AUTH_USER_MODEL)),
                ('row0column2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row0column2', to=settings.AUTH_USER_MODEL)),
                ('row1column0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row1column0', to=settings.AUTH_USER_MODEL)),
                ('row1column1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row1column1', to=settings.AUTH_USER_MODEL)),
                ('row1column2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row1column2', to=settings.AUTH_USER_MODEL)),
                ('row2column0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row2column0', to=settings.AUTH_USER_MODEL)),
                ('row2column1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row2column1', to=settings.AUTH_USER_MODEL)),
                ('row2column2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_row2column2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.RunPython(load_initial, reverse_code=unload_initial),
    ]
